AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - '**/*_spec.rb'

Metrics/ModuleLength:
  Exclude:
    - '**/*_spec.rb'

Lint/AmbiguousBlockAssociation:
  Exclude:
    - "**/*_spec.rb"
